name: build
on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Soldat game
        run: |
          mkdir soldat
          wget 'https://github.com/opensoldat/opensoldat/releases/download/continuous/linux-appimage.zip'
          unzip linux-appimage.zip
          mv opensoldat-continuous-*-x86_64.AppImage soldat/opensoldat
          chmod +x soldat/opensoldat
          rm linux-appimage.zip
          wget 'https://github.com/opensoldat/opensoldat/releases/download/continuous/linux-server-only-appimage.zip'
          unzip linux-server-only-appimage.zip
          mv opensoldatserver-continuous-*-x86_64.AppImage soldat/opensoldatserver
          chmod +x soldat/opensoldatserver
          rm linux-server-only-appimage.zip

      - name: Install packages
        run: npm ci

      - name: Build launcher
        run: npm run make

      - uses: actions/upload-artifact@v2
        with:
          name: soldat-launcher-linux
          path: out/make/zip/linux/x64/

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Soldat game
        run: |
          curl --remote-name --location 'https://github.com/opensoldat/opensoldat/releases/download/continuous/windows-build.zip'
          unzip windows-build.zip
          mv windows-build soldat
          rm windows-build.zip

      - name: Install packages
        run: npm ci

      - name: Build launcher
        run: npm run make

      - uses: actions/upload-artifact@v2
        with:
          name: soldat-launcher-windows
          path: out/make/zip/win32/x64/

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Soldat game
        run: |
          curl --remote-name --location 'https://github.com/DeathByDenim/soldat/releases/download/continuous/macos-build.zip'
          unzip macos-build.zip
          mv macos-build soldat
          rm macos-build.zip

      - name: Install packages
        run: npm ci

      - name: Build launcher
        run: npm run make

      - uses: actions/upload-artifact@v2
        with:
          name: soldat-launcher-macos
          path: out/make/zip/darwin/x64/
